spring:
  jpa:
    enabled: true
    database-platform: org.hibernate.dialect.Oracle9iDialect
  datasource:
    shard1:
      jdbc-url: jdbc:oracle:thin:@10.99.53.30:1521:UATDB7
      username: RBL_MOCK7
      password: RBL_MOCK7
      driver-class-name: oracle.jdbc.OracleDriver
    shard2:
      jdbc-url: jdbc:oracle:thin:@10.99.63.61:1521:uatdb4
      username: RBL_BACPS
      password: RBL_BACPS
      driver-class-name: oracle.jdbc.OracleDriver
    shard3:
      jdbc-url: jdbc:oracle:thin:@10.99.63.61:1521:uatdb4
      username: RBL_BACPS
      password: RBL_BACPS
      driver-class-name: oracle.jdbc.OracleDriver
